id: P000557
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:46:47.362747
source_metadata:
  id: bdr:W1KG16214
  title: ལེགས་བཤད་འོད་དཀར་འཕྲེང་བ། ༼༡༤༽
  author: ''
  volumes:
    46beb3c99491463b9d405c5a8489d779:
      image_group_id: I1KG16248
      title: Volume 1 of legs bshad 'od dkar 'phreng ba/ (14)
      volume_number: 1
      total_pages: 480
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
